name: Branch Pruning

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  prune:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Prune Branches
        run: |
          git fetch --prune
          git branch --merged origin/main | grep -v "main" | xargs -n 1 git push --delete origin
